# Generated by Django 5.1.7 on 1982-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_created_at_cartitem_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipment',
            name='items',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
